### PR TITLE
Allow agent server_url configuration

### PR DESCRIPTION
**Pull request by tom-krieger**
There are 3 different API URLs available for the Lacework agent. This URL should be configurable.

### CODE REVIEW

**Comment by ipcrm** [comment]
@tom-krieger thx for this! I see acceptance tests are failing; from what I can tell, separate from the changes here. I'm wondering if 14.04 should just be removed.  https://app.travis-ci.com/github/ipcrm/ipcrm-lacework/jobs/584900545

**Comment by tom-krieger** [comment]
I would first remove all OSes which are no longer supported by the Lacework agent. With Ubuntu 14.04 it seems that there are no updates and no Lacework agent available available. This results in an error code 100 of apt-get update.

I have issues to get the acceptance tests working on my Macbook. Some of the docker containers have issues to start the Lacework service. But on my on-prem VMs it works with exactly these OSes. Btw. the Docker Ubuntu 18.04 image does not work at all in my environment. It seems to be broken. I will have a look into the unit tests.

I used the changed module to roll out all my Lacework agents and it worked like a charm.

Maybe we shouöd add tasks and/or a plan fore using Bolt if there's no Puppet Agent available?

**Comment by ipcrm** [comment]
Added #8 for Bolt. I agree to have that would be great! Just don't want to overload this PR.

**Review by ipcrm — APPROVED** [review]
🔥

**Pull request merged**
